INSERT INTO public.consultoria_clientes (nome_negocio,nicho,cidade,whatsapp,decisor,tipo_cobranca,valor_fee,status,data_fechamento,responsavel_imersao,legado,github_url,projeto_legado) VALUES
('Vox2You','Outros','—','','Abílio / Úrsula','projeto_fechado',0,'encerrado',now(),'victor',true,'https://github.com/VictorCamisa/empreenda-hub-connect','Completo'),
('Taubaté Chopp','Outros','—','','Alexandre','projeto_fechado',0,'convertido_recorrente','2025-08-26'::timestamptz,'victor',true,'https://github.com/VictorCamisa/ashbyreal-26032179','Custom'),
('Larifa','Outros','—','','—','projeto_fechado',0,'convertido_recorrente',now(),'victor',true,'https://github.com/VictorCamisa/larifa-storefront-dash','Ecommerce'),
('Sollaris','Outros','—','','Ana','projeto_fechado',0,'convertido_recorrente',now(),'victor',true,'https://github.com/VictorCamisa/sollarisjoias','Sollaris'),
('Toko Veículos','Lojas de carro','—','','Anderson Campos','projeto_fechado',0,'convertido_recorrente','2025-09-30'::timestamptz,'victor',true,'https://github.com/VictorCamisa/toko-final','Completo, Toko'),
('Clauber Veículos','Lojas de carro','—','','Clauber','projeto_fechado',0,'encerrado','2025-08-14'::timestamptz,'victor',true,NULL,'Completo'),
('Invest','Lojas de carro','—','','Dhiego / José','projeto_fechado',0,'convertido_recorrente',now(),'victor',true,'https://github.com/VictorCamisa/investveiculos','Invest'),
('Gabriel Autos','Lojas de carro','—','','Gabriel','projeto_fechado',0,'encerrado','2025-10-09'::timestamptz,'victor',true,'https://github.com/VictorCamisa/gabriel-auto','Completo'),
('Danelli','Outros','—','','Gabriela / Guto','projeto_fechado',0,'encerrado',now(),'victor',true,'https://github.com/VictorCamisa/remix-of-im-vel-prime-ux','Danelli'),
('Blend','Outros','—','','Leona','projeto_fechado',0,'encerrado','2025-11-21'::timestamptz,'victor',true,NULL,'CRM + Disparador'),
('AXIS','Outros','—','','Lucas','projeto_fechado',0,'encerrado',now(),'victor',true,NULL,'Completo'),
('GreenLub','Outros','—','','Marcos','projeto_fechado',0,'encerrado','2025-09-01'::timestamptz,'victor',true,'https://github.com/VictorCamisa/shape-your-universe','Completo, Greenlub'),
('Filaretti Imobiliária','Outros','—','','Mario Filaretti','projeto_fechado',0,'convertido_recorrente','2025-08-21'::timestamptz,'victor',true,'https://github.com/VictorCamisa/imobiliariafilaretti','Completo'),
('Matheus Veículos','Lojas de carro','—','','Matheus Almeida','projeto_fechado',0,'convertido_recorrente','2025-11-27'::timestamptz,'victor',true,'https://github.com/VictorCamisa/autonomo-insight','Sistema Completo'),
('Up! Suplementos','Outros','—','','Maurício','projeto_fechado',0,'encerrado','2025-09-03'::timestamptz,'victor',true,NULL,'Completo, Tráfego Pago'),
('WA','Outros','—','','Mayte','projeto_fechado',0,'convertido_recorrente',now(),'victor',true,'https://github.com/VictorCamisa/wa-transportes','WA'),
('Dra Taysa','Odonto','—','','Taysa','projeto_fechado',0,'encerrado','2025-10-22'::timestamptz,'victor',true,'https://github.com/VictorCamisa/taysadiasorto','Completo, Taysa Dias'),
('Vacinas.net','Outros','—','','Marcos Tendler','projeto_fechado',0,'encerrado',now(),'victor',true,NULL,'Vacinas'),
('Consultora de Vinhos','Outros','—','','Vanessa','projeto_fechado',0,'encerrado','2025-10-29'::timestamptz,'victor',true,NULL,'CRM'),
('Doceria Vila','Outros','—','','Vivian','projeto_fechado',0,'convertido_recorrente',now(),'victor',true,'https://github.com/VictorCamisa/doce-magia-gestor','Completo, Doces Vila'),
('Vale Repasse','Lojas de carro','—','','Wesley','projeto_fechado',0,'encerrado','2025-09-13'::timestamptz,'victor',true,NULL,'Completo');