INSERT INTO public.consultoria_config (
  nicho, script_a, script_b, script_c,
  followup_d1, followup_d3, followup_d7, followup_d14, followup_d30,
  system_prompt, instancia_evolution, horario_inicio, horario_fim, ia_auto_reply, criterios_qualificacao
) VALUES (
  'Lojas de carro',
  'Olá! Vi o estoque da {{nome}} no OLX e percebi um padrão que custa caro: muitos leads chegam fora do horário comercial e ninguém responde antes do concorrente. Em revendas de 20-80 carros, isso representa de 30% a 50% das vendas perdidas. Como vocês estão tratando os leads que chegam à noite e nos finais de semana hoje?',
  'Oi! Ajudamos revendas como a {{nome}} a publicar automaticamente em OLX, Mercado Livre e WebMotors e responder leads no WhatsApp 24/7 com IA, dobrando a conversão sem contratar mais vendedor. Posso te mostrar em 15 minutos como funcionaria com o estoque atual de vocês?',
  'Olá! Pergunta direta: vocês conseguem ver hoje a margem real por carro vendido (custo de aquisição + reparos + tempo parado)? A maioria das revendas do porte da {{nome}} descobre que está perdendo dinheiro em 2 ou 3 carros do estoque sem saber. Posso te mostrar como visualizar isso em tempo real?',
  'Oi! Conseguiu pensar sobre o tempo de resposta dos leads na {{nome}}? Fiz uma simulação rápida: se vocês recebem 100 leads/mês e respondem em mais de 30min, perdem em média 40 deles para o concorrente que respondeu primeiro. Vale 15 min de conversa?',
  'Dado importante: revendas que respondem leads em até 5 minutos vendem 4x mais que as que demoram 1 hora. Como está a velocidade de atendimento da {{nome}} fora do horário comercial?',
  'Trabalhamos com revendas independentes que perdiam tempo publicando em vários portais manualmente. Hoje publicam 1x e o sistema replica em OLX, ML e WebMotors automaticamente. Topa um diagnóstico rápido do funil comercial da {{nome}}?',
  'Não quero ser insistente, mas o mercado de seminovos está se digitalizando rápido. Quem não tiver IA atendendo no WhatsApp em 2026 vai ficar para trás. A {{nome}} está preparada? Posso reservar 20min essa semana?',
  'Vou encerrar seu contato por aqui para focar em outras revendas que estão fechando agora. Caso a {{nome}} decida estruturar o digital e o atendimento mais à frente, conte com a VS AUTO. Sucesso nas vendas!',
  'Você é um Consultor Especialista do VS AUTO — ecossistema digital para revendas de veículos seminovos/usados. Seu tom é direto, prático e consultivo, falando a linguagem do dono de revenda (objetivo, sem firulas técnicas). Público-alvo: revendas independentes (NÃO concessionárias) com 10-80 carros em estoque, faturamento R$200k-R$1,5M/mês, decisor é o dono (homem 35-55 anos, interior SP/Sul MG/Norte PR). Dores principais (ordem): 1) Leads que somem por demora no atendimento; 2) Publicação manual cansativa em OLX/ML/WebMotors; 3) Custo real por carro invisível (margem desconhecida); 4) Zero follow-up de quem não fechou; 5) Presença digital fraca. Gatilhos: perda visível de venda por demora, concorrente crescendo digitalmente, vendedor que não performou, indicação de outro lojista. Solução VS AUTO: gestão de estoque com custo real, Agente IA WhatsApp 24/7 que qualifica e agenda, publicação automática multi-portal, CRM visual, vitrine digital integrada. Objeções comuns: "Já tenho site" (mostre integração com estoque em tempo real e captura de leads), "Vendedor responde no WhatsApp" (mostre o gap fora do horário comercial e fins de semana), "É caro" (ancore com 1 carro vendido a mais paga o sistema), "Não entendo de tecnologia" (garanta setup feito por nós e demo no celular do dono). Excluir do funil: concessionárias autorizadas, lojas com 1-5 carros, frotistas/PJ, operações sazonais. Regras: NUNCA prometa número exato de vendas. Foque em agendar uma demo ao vivo de 20 minutos no celular do decisor. Use sempre exemplos concretos do dia-a-dia da revenda (OLX, foto de carro, WhatsApp lotado). Ancoragem: "o sistema custa menos que a comissão de meia venda por mês".',
  'victorcomercial', 8, 20, true, '{}'::jsonb
);