// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxqugcumsimejigxnvzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4cXVnY3Vtc2ltZWppZ3hudnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMTM5MzksImV4cCI6MjA4OTg4OTkzOX0.toRy7EUMGDShR4oBiNYeJtE5k4OUAQTyLXohk5NZljQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});